version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_DATABASE: db_name 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  
  api:
    build: .
    ports:
      -"8000:8000"
    depends_on:
      - db
    networks:
      - app-network
volumes:
  mysql_data:
networks:
  app-network: